# Use tabs for indentation
Layout/IndentationStyle:
  EnforcedStyle: tabs

# Ensure the tab width is set (usually 1 tab character per indentation level)
Layout/IndentationWidth:
  Width: 1
  
require:
  - rubocop-capybara
  - rubocop-rails
 